### ISSUE TITLE
Install via CocoaPods

### ISSUE THREAD

**Issue by Lintom** [joomcode/BottomSheet#4]
Hello. How install this lib via CocoaPods?

**Comment by mikhailmaslo** [comment]
Hello! Unfortunately, it's only available through [Swift Package Manager](https://www.swift.org/package-manager/)

**Comment by snaillovesmile** [comment]
CocoaPods support  please...

**Comment by covantex-ios-mp** [comment]
CocoaPods support please...

**Comment by mikhailmaslo** [comment]
Hey, it's been a while, I see that there are still a lot of developers who uses CocoaPods, so I've just added it

Now, you can add `BottomSheet` through CocoaPods, just add this line to your Podfile
```ruby
pod 'BottomSheet', :git => 'https://github.com/joomcode/BottomSheet'
```

If you need a fixed version, you can use tag:
```ruby
pod 'BottomSheet', :git => 'https://github.com/joomcode/BottomSheet', :tag => '2.0.2'
```

I wasn't able to push it to cocoapods registry because 'BottomSheet' has already been taken, so it's not possible to use convenient version syntax, like:
```ruby
pod 'BottomSheet', '~>2.0'
```

For now, I'll close this issue, let me know if the method above doesn't work for you

**Comment by covantex-ios-mp** [comment]
Thank you @mikhailmaslo.
